apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgeai

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - ollama-deployment.yaml
  - deployment.yaml
  - service.yaml
