apiVersion: v1
kind: Service
metadata:
  name: forgeai
  namespace: forgeai
spec:
  selector:
    app: forgeai
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
  # NodePort로 외부 노출 시 아래 주석 해제 후 type: NodePort 로 변경
  # type: NodePort
  # ports:
  #   - name: http
  #     port: 80
  #     targetPort: 8000
  #     nodePort: 30800
